import os

POSTGRES_USER = os.getenv("POSTGRES_USER", "your_db_user")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "your_db_password")
POSTGRES_DB = os.getenv("POSTGRES_DB", "your_db_name")
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "db")
POSTGRES_PORT = os.getenv("POSTGRES_PORT", 5438)

SQLALCHEMY_DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
